### ISSUE TITLE
日本語入力中にバックスペースキーを使うとリクエストエラーが発生する

### ISSUE THREAD

**Issue by yocaji** [yocajii/sawara#6]
## 再現手順

1. 「テスト」と入力
2. バックスペースキー2回押下
3. Enter
4. Ctrl+d

```
❯ sawara

                                 S a w a r a 🐟
********************************************************************************
Hint 1: To send your message, press "Enter" and "Ctrl + d".
Hint 2: To exit this conversation, press "Ctrl + d" without any message.
********************************************************************************

You:
テス
/home/yocajii/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/sawara-0.1.1/lib/sawara/talk.rb:39:in `sub': invalid byte sequence in UTF-8 (ArgumentError)

      content = $stdin.readlines.join.sub(/\n*$/, '')
                                          ^^^^^^^^^^
        from /home/yocajii/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/sawara-0.1.1/lib/sawara/talk.rb:39:in `await_user_content'
        from /home/yocajii/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/sawara-0.1.1/lib/sawara/talk.rb:15:in `block in start'
        from /home/yocajii/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/sawara-0.1.1/lib/sawara/talk.rb:14:in `loop'
        from /home/yocajii/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/sawara-0.1.1/lib/sawara/talk.rb:14:in `start'
        from /home/yocajii/.rbenv/versions/3.2.1/lib/ruby/gems/3.2.0/gems/sawara-0.1.1/exe/sawara:8:in `<top (required)>'
        from /home/yocajii/.rbenv/versions/3.2.1/bin/sawara:25:in `load'
        from /home/yocajii/.rbenv/versions/3.2.1/bin/sawara:25:in `<main>'
```

**Comment by yocaji** [comment]
```
You:
テス  

[37, 46] in /home/yocajii/work/sawara/lib/sawara/talk.rb
   37:       puts
   38:       puts 'You:'
   39:       # content = $stdin.readlines.join.sub(/\n*$/, '')
   40:       content = $stdin.readlines
   41:       byebug
=> 42:       @messages << { role: 'user', content: }
   43:       content
   44:     end
   45:
   46:     def await_assistant_content(client)
(byebug) content
["テス\xE3\n"]
```

**Comment by yocaji** [comment]
#7 にて対応済み
